ldap.url=ldap://localhost:389
ldap.base=dc=example,dc=com
ldap.principal=cn=admin,dc=example,dc=com
ldap.password=adminpassword

application.jwt.secret.key=a469447b-ad0c-4ff4-8702-45b739030a73
application.jwt.access.token.validity.min=60
application.jwt.refresh.token.validity.min=1440

application.poc.hikari.username=pocdb
application.poc.hikari.password=123456
application.poc.hikari.jdbcUrl=jdbc:postgresql://localhost:5432/pocdb
application.poc.hikari.poolName=hikari-pool-pocdb
application.poc.hikari.connectionTimeout=30000
application.poc.hikari.idleTimeout=10000
application.poc.hikari.minimumIdle=1
application.poc.hikari.maximumPoolSize=5
application.poc.hikari.maxLifetime=0

application.poc.hibernate.connection.release_mode=after_transaction
application.poc.hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
application.poc.hibernate.order_by.default_null_ordering=last
application.poc.hibernate.database-platform=org.hibernate.dialect.PostgreSQLDialect

application.poc.liquibase.changelog=classpath:liquibase/poc.xml
application.poc.liquibase.contexts=dev