enum CustomException {
  AUTHENTICATION_EXCEPTION = 1,
  EXPIRED_AUTHORIZATION_EXCEPTION,
  SIGNATURE_AUTHORIZATION_EXCEPTION,
  AUTHORIZATION_EXCEPTION,
  REFRESH_TOKEN_EXCEPTION,
  API_LOCK_EXCEPTION,
  METHOD_ARGUMENT_NOT_VALID_EXCEPTION,
  HTTP_MESSAGE_NOT_READABLE_EXCEPTION,
  INTERNAL_SERVER_ERROR = 9,
  UNKNOWN_VEHICULE = 10,
  REJECT_NOT_ORPHAN = 11,
  WHITE_LIST_EXCEPTION = 12,
  FILE_SIZE_EXCEEDED = 14,
  TOLL_LANE_EXCEPTION = 15
}

export default CustomException;
